// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
	DATABASE_ID: string;
	CLOUDFLARE_D1_API_TOKEN: string;
	CLOUDFLARE_D1_ACCOUNT_ID: string
}
